{% set data = load_setup_py_data() %}

package:
  name: datamine
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python
    - requests
    - urllib3
    - pandas
    - tqdm
    - futures-compat

test:
  imports:
    - datamine
    - datamine.io
    - datamine.utils
    - datamine.loaders

about:
  home: https://github.com/CMEGroup/datamine_python
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python connector for the CME DataMine service.'
